# vim:sw=2:et:

sudo: false

language: erlang
otp_release:
  - "19.3"
  - "20.0"
  - "21.0"

script:
  - make escript FULL=1
  - ./hexpm search rabbit_common
  - make tests FULL=1

addons:
  apt:
    packages:
      - p7zip-full
cache:
  apt: true

notifications:
  email:
    - alerts@rabbitmq.com
