# vim:sw=2:et:

sudo: false

language: erlang
otp_release:
  - "21.3"
  - "22.3"
  - "23.0"

script:
  - make escript FULL=1
  # We do the following command to fetch the Hex plugin.
  - ./hexpm help || (cat rebar3.crashdump && exit 1)
  - make tests FULL=1

addons:
  apt:
    packages:
      - p7zip-full
cache:
  apt: true

notifications:
  email:
    - alerts@rabbitmq.com
